[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Javier Aguilera <jaguilerapuerta@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
